INSERT INTO LOG.JMS_MESSAGE_TYPE 
(ID,IDEMPOTENT,LOGGED,NAME     ,SINCE       ) VALUES
(1 ,FALSE     ,TRUE  ,'urn:event-type:<UNKNOWN>','1970-01-01')
;
INSERT INTO LOG.JMS_MESSAGE_TYPE 
(ID,IDEMPOTENT,LOGGED,NAME           ,SINCE       ) VALUES
(2 ,TRUE      ,TRUE  ,'REGISTER_ITEM','1970-01-01')
;
INSERT INTO LOG.JMS_MESSAGE 
(ID,GUID                 ,ID_JMSMESSAGETYPE,PROCESSING_STATE,RECEIVED_ON                    ,COMPLETED_ON,CONTENT,ERROR_TYPE,ERROR_MESSAGE,ERROR_STACKTRACE) VALUES
(-1,'UUID-123-67-8997-98',2                ,'IN_PROGRESS'   ,'1970-01-01 01:01:01.000000000',NULL        ,'TEST' ,NULL      ,NULL         ,NULL            )
;
